import os
os.system("clear ")
print(" ____               _             _____ _ _ _ ")
print("|  _ \ ___ _ __ ___(_) __ _ _ __ | ____| (_) |_ ___ ")
print("| |_) / _ \ '__/ __| |/ _` | '_ \|  _| | | | __/ _ \ ")
print("|  __/  __/ |  \__ \ | (_| | | | | |___| | | ||  __/ ")
print("|_|   \___|_|  |___/_|\__,_|_| |_|_____|_|_|\__\___| ")
os.system("apt update && apt upgrade -y ")
os.system("pkg install python ")
os.system("pip install speedtest-cli ")
os.system("clear ")
os.system("speedtest-cli ")
print(" ________________ ")
print("< Test-net Done! > ")
print(" ---------------- ")
print("        \   ^__^ ")
print("         \  (oo)\_______ ")
print("            (__)\       )\/\ ")
print("                ||----w | ")
print("                ||     || ")
